name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-openssl:
    
    runs-on: [ubuntu-latest]
    
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt-get install libssl-dev libcurl4-openssl-dev libgumbo-dev
    - name: Make
      env:
        CC: ${{ matrix.compiler }}
      run: cd src/ && make
      
  build-gnutls:
    runs-on: [ubuntu-latest]
    
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt-get install libgnutls28-dev libcurl4-gnutls-dev libgumbo-dev
    - name: Make
      env:
        CC: ${{ matrix.compiler }}
      run: cd src/ && make
      
