name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

strategy:
  compiler: [gcc, clang]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build dependencies
      run: sudo apt-get install libssl-dev libcurl4-openssl-dev libgumbo-dev
    - name: make
      env:
        CC: ${{ matrix.compiler }}
      run: cd src/ && make
